name: CI

on: [push, pull_request]

jobs:
  windows:
    strategy:
      matrix:
        os: windows-2019
        include:
          - os: windows-2019
            sysversion: "10.0.18362.0"
    runs-on: ${{ matrix.os }}
    steps:
    - name: "Clone Repository"
      uses: actions/checkout@v1
    - name: "Configure Project"
      run: |
        cmake -H"." -B"build/temp" -G"Visual Studio 16 2019" -A"x64" -T"host=x64" -DCMAKE_SYSTEM_VERSION=10.0 -DCMAKE_PACKAGE_NAME=StreamFX -DCMAKE_INSTALL_PREFIX="build/distrib" -DCMAKE_PACKAGE_PREFIX="build/package" -DOBS_DOWNLOAD=true
    - name: "Build Project"
      run: |
        cmake -H. -B"build/temp" --config RelWithDebInfo
    - name: "Package Project"
      run: |
        cmake -H. -B"build/temp" --config RelWithDebInfo --target PACKAGE_7Z
        cmake -H. -B"build/temp" --config RelWithDebInfo --target PACKAGE_ZIP
    - name: "Package Installer (Prereqs)"
      run: |
        curl "-kL" "https://cdn.xaymar.com/ci/innosetup-6.0.3.exe" "-f" "--retry" "5" "-o" "inno.exe"
        .\inno.exe /VERYSILENT /SP- /SUPPRESSMSGBOXES /NORESTART
    - name: "Package Installer (Compile)"
      run: |
        & 'C:\Program Files (x86)\Inno Setup 6\ISCC.exe' /Qp ".\build\64\installer.iss"
    - name: "Upload Artifacts"
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.os }}
        path: build/package
